"""remigration.

Revision ID: 299cee898d14
Revises: 4c099edae0a9
Create Date: 2024-07-20 16:12:42.829708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299cee898d14'
down_revision = '4c099edae0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('features')
        batch_op.drop_column('challenges')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenges', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('features', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
